pipeline {
    agent any
    tools { 
        maven 'Lab Maven'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                dir('./starter') {
                    sh 'mvn -B clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('./starter') {
                    sh 'mvn -B test'
                }
            }
            post {
                always {
                    junit 'target/test-reports/*.xml'
                }
            }
        }
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }
    }
}
